schema = 1

[generator]
revision = "e05aee6de1d1614d752b4d1b1d26a49ac2c5ef91"
repository = "tailrocks/homebrew-tablerock"

[workflow]
runners = "both"
automatic = "both"
github_runner = "ubuntu-24.04"
velnor_labels = ["self-hosted", "velnor-target-mvp"]
default_branch = "main"

[[static_files]]
file = ".github/workflows/package-update.yml"
source = ".github-gen/sources/workflows/package-update.yml"

[[static_files]]
file = ".github/workflows/update-preview.yml"
source = ".github-gen/sources/workflows/update-preview.yml"

